In [2]:
%matplotlib inline

import matplotlib.pyplot as plt
import pandas as pd
import datetime
from datetime import datetime
import numpy 
import os

In [3]:
try:
    __thisdir__ = os.path.dirname(os.path.abspath(__file__))
except NameError as error:
    __thisdir__ = "."
    
#create the direcotry to store the data if not existed
data_process = os.path.join(__thisdir__, "less_big.csv")
beer_data_df = pd.read_csv(data_process)

In [4]:
beer_data_df.head()

,Unnamed: 0,beer_style_id,beer_new_name,beer_style,ibu_Min,ibu_Max,abv_Min,abv_Max,srm_Min,srm_Max,...,review_time,review_overall,review_aroma,review_appearance,review_profilename,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,0,0,Classic English-Style Pale Ale,English Pale,20,40,4.5,5.5,5,5,...,1294324816,5.0,4.5,4.5,JamesS,5.0,4.0,Lawn Mower Pale Ale,5.0,61478
1,1,0,Classic English-Style Pale Ale,English Pale,20,40,4.5,5.5,5,5,...,1283115229,4.5,4.0,4.0,brundo4,4.0,3.5,Lawn Mower Pale Ale,5.0,61478
2,4,0,Classic English-Style Pale Ale,English Pale,20,40,4.5,5.5,5,5,...,1130157499,4.5,3.5,4.0,oberon,3.5,4.0,Moon Dance Pale Ale,4.2,26562
3,5,0,Classic English-Style Pale Ale,English Pale,20,40,4.5,5.5,5,5,...,1314903858,3.5,3.5,3.5,smcolw,4.0,4.0,Skyelight,3.8,71157
4,6,0,Classic English-Style Pale Ale,English Pale,20,40,4.5,5.5,5,5,...,1311007143,3.5,3.0,3.0,AgentMunky,4.0,4.0,Skyelight,3.8,71157

In [5]:
#Data clean up

In [6]:
beer_data_cleaned = beer_data_df.drop(columns=['beer_style_id','beer_new_name','brewery_id','beer_beerid'])

In [7]:
beer_data_cleaned.head()

,Unnamed: 0,beer_style,ibu_Min,ibu_Max,abv_Min,abv_Max,srm_Min,srm_Max,og_Min,fg_Min,...,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,review_palate,review_taste,beer_name,beer_abv
0,0,English Pale,20,40,4.5,5.5,5,5,1.04,1.008,...,Broad Ripple Brew Pub,1294324816,5.0,4.5,4.5,JamesS,5.0,4.0,Lawn Mower Pale Ale,5.0
1,1,English Pale,20,40,4.5,5.5,5,5,1.04,1.008,...,Broad Ripple Brew Pub,1283115229,4.5,4.0,4.0,brundo4,4.0,3.5,Lawn Mower Pale Ale,5.0
2,4,English Pale,20,40,4.5,5.5,5,5,1.04,1.008,...,Moon River Brewing Company,1130157499,4.5,3.5,4.0,oberon,3.5,4.0,Moon Dance Pale Ale,4.2
3,5,English Pale,20,40,4.5,5.5,5,5,1.04,1.008,...,Isle Of Skye Brewery,1314903858,3.5,3.5,3.5,smcolw,4.0,4.0,Skyelight,3.8
4,6,English Pale,20,40,4.5,5.5,5,5,1.04,1.008,...,Isle Of Skye Brewery,1311007143,3.5,3.0,3.0,AgentMunky,4.0,4.0,Skyelight,3.8

In [23]:
ber_brewery_rev_df = beer_data_cleaned[["brewery_name","review_overall","beer_name"]]

In [24]:
brewries_df = ber_brewery_rev_df.groupby("brewery_name").count()

In [26]:
len(brewries_df)

3031

In [31]:
brewries_df.sort_values(by=['review_overall'],ascending=False).head(20)

                                    review_overall  beer_name
brewery_name
Boston Beer Company (Samuel Adams)           28109      28109
Stone Brewing Co.                            26306      26306
Sierra Nevada Brewing Co.                    25072      25072
Bell's Brewery, Inc.                         22366      22366
Rogue Ales                                   18355      18355
Founders Brewing Company                     15882      15882
Southern Tier Brewing Company                13209      13209
Great Divide Brewing Company                 13070      13070
Avery Brewing Company                        11325      11325
Goose Island Beer Co.                        10410      10410
TrÃ¶egs Brewing Company                        9258       9258
Flying Dog Brewery                            8500       8500
New Belgium Brewing                           8228       8228
Great Lakes Brewing Company                   7623       7623
Matt Brewing Company                          7207       7207
Harpoon Brewery                               7007       7007
Weyerbacher Brewing Co.                       6985       6985
Port Brewing Company / Pizza Port             6570       6570
Terrapin Beer Company                         6390       6390
Mikkeller ApS                                 6313       6313

In [32]:
beer_df = ber_brewery_rev_df.groupby("beer_name").count()
len(beer_df)

20033

In [42]:
top_100_beer_rev = beer_df.sort_values(by=['review_overall'],ascending=False).head(100)

In [38]:
beer_rev_df = ber_brewery_rev_df.groupby("beer_name").mean()

In [49]:
beer_review_count = (top_100_beer_rev[["brewery_name"]]).rename(columns={'brewery_name': 'review_count'})

In [50]:
beer_review_count.head()

                               review_count
beer_name
Sierra Nevada Celebration Ale          2999
Two Hearted Ale                        2727
Stone Ruination IPA                    2702
Arrogant Bastard Ale                   2702
Sierra Nevada Pale Ale                 2587

In [86]:
top_100_beers = pd.merge(beer_review_count,beer_rev_df,how="inner",left_index=True, right_index=True)

In [87]:
top_100_beers.head()

                               review_count  review_overall
beer_name
Sierra Nevada Celebration Ale          2999        4.168556
Two Hearted Ale                        2727        4.330216
Stone Ruination IPA                    2702        4.161547
Arrogant Bastard Ale                   2702        4.078090
Sierra Nevada Pale Ale                 2587        4.245845

In [88]:
beer_brewrey_df= ber_brewery_rev_df[["brewery_name","beer_name"]].drop_duplicates()
beer_brewrey_df.set_index("beer_name", inplace=True)

In [89]:
beer_brewrey_df.head()

                                   brewery_name
beer_name
Lawn Mower Pale Ale       Broad Ripple Brew Pub
Moon Dance Pale Ale  Moon River Brewing Company
Skyelight                  Isle Of Skye Brewery
Red Cuillin                Isle Of Skye Brewery
Brew Eyed Blond                       Brew Eyed

In [90]:
top_100_beers = pd.merge(top_100_beers,beer_brewrey_df,how="inner",left_index=True, right_index=True)

In [91]:
top_100_beers.sort_values(by=['review_overall'],ascending=False, inplace=True)
top_100_beers.head()

,review_count,review_overall,brewery_name
beer_name,,,
Weihenstephaner Hefeweissbier,1980,4.516414,Bayerische Staatsbrauerei Weihenstephan
Sculpin India Pale Ale,1352,4.437870,Ballast Point Brewing Company
Founders KBS (Kentucky Breakfast Stout),1930,4.396891,Founders Brewing Company
TrÃ¶egs Nugget Nectar,1954,4.395855,TrÃ¶egs Brewing Company
Bell's Hopslam Ale,2443,4.377609,"Bell's Brewery, Inc."

In [92]:
beers_by_brewery = (ber_brewery_rev_df[["brewery_name","beer_name"]].drop_duplicates()).groupby("brewery_name").count()

In [93]:
beers_by_brewery.rename(columns={'beer_name': 'beers_released'},inplace=True)
beers_by_brewery.sort_values(by=['beers_released'],ascending=False,inplace=True)
beers_by_brewery.head()

                                   beers_released
brewery_name
Goose Island Beer Co.                         237
Minneapolis Town Hall Brewery                 173
Iron Hill Brewery & Restaurant                172
Port Brewing Company / Pizza Port             167
Cigar City Brewing                            151

In [97]:
test = pd.merge(top_100_beers,beers_by_brewery,on="brewery_name",right_index=True,how="inner")

In [98]:
test

,review_count,review_overall,brewery_name,beers_released
beer_name,,,,
Weihenstephaner Hefeweissbier,1980,4.516414,Bayerische Staatsbrauerei Weihenstephan,10
Sculpin India Pale Ale,1352,4.437870,Ballast Point Brewing Company,48
Pale Ale,1833,3.731588,Ballast Point Brewing Company,48
Founders KBS (Kentucky Breakfast Stout),1930,4.396891,Founders Brewing Company,91
Founders Breakfast Stout,2501,4.354658,Founders Brewing Company,91
Founders Imperial Stout,1078,4.185993,Founders Brewing Company,91
Founders Centennial IPA,1394,4.146341,Founders Brewing Company,91
Founders Double Trouble,1164,4.096649,Founders Brewing Company,91
Founders Backwoods Bastard,1020,3.985784,Founders Brewing Company,91
Founders Dirty Bastard,1257,3.935561,Founders Brewing Company,91
Founders Devil Dancer,1066,3.733583,Founders Brewing Company,91
TrÃ¶egs Nugget Nectar,1954,4.395855,TrÃ¶egs Brewing Company,61
TrÃ¶egs Hopback Amber Ale,1052,4.184411,TrÃ¶egs Brewing Company,61
Bell's Hopslam Ale,2443,4.377609,"Bell's Brewery, Inc.",78
Two Hearted Ale,2727,4.330216,"Bell's Brewery, Inc.",78
Bell's Oberon Ale,1440,4.074306,"Bell's Brewery, Inc.",78
Bell's Kalamazoo Stout,1287,4.057498,"Bell's Brewery, Inc.",78
Bell's Special Double Cream Stout,1205,4.002905,"Bell's Brewery, Inc.",78
Bell's Expedition Stout,1692,3.953605,"Bell's Brewery, Inc.",78
Bell's Java Stout,955,3.826702,"Bell's Brewery, Inc.",78
Furious,1224,4.336601,Surly Brewing Company,31
Ayinger Celebrator Doppelbock,2068,4.299081,Privatbrauerei Franz Inselkammer KG / Brauerei...,12
AleSmith Speedway Stout,1133,4.284201,AleSmith Brewing Company,45
PÃ©chÃ© Mortel (Imperial Stout Au Cafe),1438,4.268428,Brasserie Dieu Du Ciel,53
Sierra Nevada Kellerweis Hefeweizen,1021,4.265916,Sierra Nevada Brewing Co.,101
Sierra Nevada Pale Ale,2587,4.245845,Sierra Nevada Brewing Co.,101
Northern Hemisphere Harvest Wet Hop Ale,1353,4.241685,Sierra Nevada Brewing Co.,101
Sierra Nevada Celebration Ale,2999,4.168556,Sierra Nevada Brewing Co.,101
Sierra Nevada Stout,1230,4.136992,Sierra Nevada Brewing Co.,101
Sierra Nevada Southern Hemisphere Harvest Fresh Hop Ale,1145,4.125764,Sierra Nevada Brewing Co.,101
...,...,...,...,...
Pale Ale,1833,3.731588,Upper Canada Brewing Company,8
Pale Ale,1833,3.731588,Three Troupers Brewery,2
Pale Ale,1833,3.731588,"Hidatakayama Brewing Agricultural Corporation,...",5
Pale Ale,1833,3.731588,Brewster's Brewing Co Ltd,9
Pale Ale,1833,3.731588,Schooner's Grille & Brewery,8
Pale Ale,1833,3.731588,YellowBelly Brewery & Public House,3
Pale Ale,1833,3.731588,Good People Brewing Company,15
Pale Ale,1833,3.731588,Cumberland Brews,10
Pale Ale,1833,3.731588,Blue House Mediterranean Cafe,1
Pale Ale,1833,3.731588,Amber's Brewing Co.,5
Pale Ale,1833,3.731588,Syracuse Suds Factory,4
Pale Ale,1833,3.731588,Lobethal Bierhaus,3
Pale Ale,1833,3.731588,Wig And Pen,25
Pale Ale,1833,3.731588,Flying Monkeys Craft Brewery,22
Pale Ale,1833,3.731588,Four Horsemen Brewing Company,6
Pale Ale,1833,3.731588,Double Mountain Brewery & Taproom,26
Pale Ale,1833,3.731588,Brau Brothers Brewing Co. LLC,12
Pale Ale,1833,3.731588,Croucher Brewing Co.,4
Pale Ale,1833,3.731588,JoBoy's Brew Pub,12
Pale Ale,1833,3.731588,Marmot Mesa Brewery & Ale House,4
Pale Ale,1833,3.731588,Chez Gambrinus,7
Pale Ale,1833,3.731588,Lefty's Brewing Company,4
Pale Ale,1833,3.731588,Humboldt Brews LLC,4
Pale Ale,1833,3.731588,Grogg's Pinnacle Brewing Co.,5
Pale Ale,1833,3.731588,Orlando Brewing Partners,15
Pale Ale,1833,3.731588,Zerodegrees Cardiff,5
Pale Ale,1833,3.731588,Faultline Brewing Company,8
Leffe Blonde,1119,3.643878,Abbaye de Leffe S.A.,1
Blue Moon Belgian White,1498,3.603471,Coors Brewing Company,12
Boddingtons Pub Ale,1113,3.525606,Boddingtons,2